// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8VLq25VS5sz2BiE7Y1gEUsVEpiAdnsfI',
    appId: '1:208738463007:web:f4847ce657bc6ff5d3542a',
    messagingSenderId: '208738463007',
    projectId: 'nawel-6e6ce',
    authDomain: 'nawel-6e6ce.firebaseapp.com',
    storageBucket: 'nawel-6e6ce.firebasestorage.app',
    measurementId: 'G-3EH7L9384Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPUliTqMYpogpHASV0EMcIl9xapKqQWc',
    appId: '1:208738463007:android:a9993777190cbd84d3542a',
    messagingSenderId: '208738463007',
    projectId: 'nawel-6e6ce',
    storageBucket: 'nawel-6e6ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNt_pjJuFIwlfXQK5O0OTJeEwiMiKpgI',
    appId: '1:208738463007:ios:51b3f2a03f958535d3542a',
    messagingSenderId: '208738463007',
    projectId: 'nawel-6e6ce',
    storageBucket: 'nawel-6e6ce.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFNt_pjJuFIwlfXQK5O0OTJeEwiMiKpgI',
    appId: '1:208738463007:ios:51b3f2a03f958535d3542a',
    messagingSenderId: '208738463007',
    projectId: 'nawel-6e6ce',
    storageBucket: 'nawel-6e6ce.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8VLq25VS5sz2BiE7Y1gEUsVEpiAdnsfI',
    appId: '1:208738463007:web:fafdcc616a6d702ad3542a',
    messagingSenderId: '208738463007',
    projectId: 'nawel-6e6ce',
    authDomain: 'nawel-6e6ce.firebaseapp.com',
    storageBucket: 'nawel-6e6ce.firebasestorage.app',
    measurementId: 'G-D7RDX4486M',
  );
}
